language_swap_project/language_swap/urls.py
from django.conf.urls import url
from language_swap import views

urlpatterns = [
    url(r'^$', views.index, name = "index"),
    url(r'^searchResult/$', views.searchResult, name = "result"),
    url(r'^about/$', views.about, name = "about"),
    url(r'^contactUs/$', views.contact, name = "contact"),
    url(r'^myProfile/$', views.profile, name = "myProfile"),
    url(r'^myProfile/edit/$', views.edit_profile, name = 'edit_profile'),
    url(r'^myProfile/delete/$', views.delete_account, name = 'delete_account'),
    url(r'^contactHistory/$', views.contactHistory, name = "contactHistory"),
    url(r'^rating/$', views.rating, name = "rating"),
    url(r'^emailCheck/$',views.emailCheck,name = "emailCheck"),
    url(r'^sendEmail/$', views.sendEmail, name = 'sendEmail'),
]

language_swap_project/language_swap_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from language_swap import views
from registration.backends.simple.views import RegistrationView
from language_swap.regbackend import MyRegistrationView

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^LanguageSwap/', include('language_swap.urls')),
    url(r'^accounts/register/$', MyRegistrationView.as_view(), name='registration_register'),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

language_swap_project/language_swap/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models
# Create your models here.

class Language(models.Model):
    
    LanguageName = models.CharField(max_length=120,primary_key=True)

    def __str__(self):
        return self.LanguageName


class UserProfile(models.Model):

    #these are the user details that are not in the default User model
    user = models.OneToOneField(User)

    city = models.CharField(max_length=120)

    country = models.CharField(max_length=120)

    gender = models.CharField(max_length=10,  null = True)

    #picture and hobby are optional
    picture = models.ImageField(upload_to='profile_images',blank = True)

    hobby = models.CharField(max_length=500,blank = True)

    # following lines are to calculate age from date of birth
    #age can be calculated in views.py
    dob = models.DateField(max_length=8, null = True)

    #these are the relationship attributes between user and languages
    speaks = models.ManyToManyField(Language,related_name="speaks")

    practices = models.ManyToManyField(Language,related_name='practices')

    def __str__(self):
        return self.user.username


class Contact(models.Model):
    sourceUser = models.ForeignKey(UserProfile,related_name='source')
    contactedUser = models.ForeignKey(UserProfile,related_name='contacted')

    #by default, if a user appears on your contact history, he/she is not rated by default
    score = models.IntegerField(default=0)

language_swap_project/language_swap/forms.py
from django import forms
from language_swap.models import UserProfile, Language
from registration.forms import RegistrationForm
from language_swap.helperFunctions import getUserAge, placesReverseGeocoder

class UserRegistrationForm(RegistrationForm):
    username = forms.CharField(max_length=150, required=False, widget=forms.HiddenInput())

    # Extra fields
    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=30)
    city = forms.CharField(max_length=120, required=False, widget=forms.HiddenInput())
    country = forms.CharField(max_length=120, required=False, widget=forms.HiddenInput())
    places = forms.CharField(widget=forms.TextInput(attrs={'id': 'gMapsAutocomplete'}))
    speaks = forms.ModelMultipleChoiceField(queryset=Language.objects.all().order_by('LanguageName'))
    practices = forms.ModelMultipleChoiceField(queryset=Language.objects.all().order_by('LanguageName'))
    gender = forms.ChoiceField(widget=forms.RadioSelect, choices=[("male","Male"), ("female", "Female"), ("other","Other")])
    dob = forms.DateField()

    # Sets username to given email
    def clean_email(self):
        email = self.cleaned_data['email']
        self.cleaned_data['username'] = email
        return email

    def clean_dob(self):
        dob = self.cleaned_data['dob']
        if getUserAge(dob)<13:
            raise forms.ValidationError(u'To create an account you must be at least 13 years old.')
        return dob

    def clean_places(self):
        places = self.cleaned_data['places']
        user_loc = placesReverseGeocoder(places)

        # If the function returns True, sets the city and the country
        # Otherwise generates an error
        if user_loc['status']:
            self.cleaned_data['city'] = user_loc['city'].lower()
            self.cleaned_data['country'] = user_loc['country'].lower()
        else:
            raise forms.ValidationError(u'An error has occurred while fetching the places. Please try again')
        return places

class EditProfileForm(forms.ModelForm):
    places = forms.CharField(widget=forms.TextInput(attrs={'id': 'gMapsAutocomplete'}))

    class Meta:
        model = UserProfile
        fields = ('picture','hobby','places')
        exclude = ('first_name','last_name','username','password','email')

    def clean_places(self):
        places = self.cleaned_data['places']
        user_loc = placesReverseGeocoder(places)

        # If the function returns True, sets the city and the country
        # Otherwise generates an error
        if user_loc['status']:
            self.cleaned_data['city'] = user_loc['city'].lower()
            self.cleaned_data['country'] = user_loc['country'].lower()
        else:
            raise forms.ValidationError(u'An error has occurred while fetching the places. Please try again')
        return places

class DeleteAccountForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = ()

language_swap_project/language_swap/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from language_swap.models import User, UserProfile, Language, Contact
from language_swap.forms import EditProfileForm, DeleteAccountForm
from language_swap.helperFunctions import getUserDetails, getUserRating, placesReverseGeocoder, sendEmailFunction
from django.contrib.auth.decorators import login_required
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.urls import reverse
import json


def index(request):
    context_dict = {'languages': []}

    # Get all languages from the database
    languages = Language.objects.all().order_by('LanguageName')

    # Populate the context_dictionary with all the languages
    for language in languages:
        context_dict['languages'].append(str(language).lower())

    return render(request, 'language_swap/index.html', context_dict)


def searchResult(request):
    context_dict = {'errors':[], 'users' : {}}
    errors = False

    # Get the parameters passed in the URL
    practicingLanguage = request.GET.get('practicingLanguage', '').encode('utf-8').lower().strip()
    spokenLanguage = request.GET.get('spokenLanguage', '').encode('utf-8').lower().strip()

    # get the place from the Get request and pass it as a parameter to the placesReverseGeocoder function
    places = placesReverseGeocoder(request.GET.get('places', ''))

    # If the function returns True, retrieve the city and the country Otherwise generate an error
    if places['status']:
        city = places['city']
        country = places['country']
    else:
        errors = True
        context_dict['errors'].append("An error has occurred while fetching the places.")


    # Try to retrieve the selected languages
    try:
        practicing = Language.objects.get(LanguageName = practicingLanguage)
        spoken = Language.objects.get(LanguageName = spokenLanguage)
    except Language.DoesNotExist:
        errors = True
        context_dict['errors'].append("An error has occurred while fetching the languages.")

    # If an error occurs while selecting the languages, do not perform the Query and
    # just return the error message
    if not errors:
        resultUsers = UserProfile.objects.filter(practices= spoken, speaks = practicing, country = country, city = city)

        # If there are results to the Query, retrieve users details
        if resultUsers.exists():
            for resultUser in resultUsers:
                # Check if the user is logged in. We don't want to show the logged in user in the result page
                if request.user.is_authenticated():
                    # If it is not logged in, add it to the result context dictionary
                    if request.user != resultUser.user:
                        context_dict['users'].update(getUserDetails(resultUser))
                else:
                    context_dict['users'].update(getUserDetails(resultUser))
        else:
            context_dict['errors'].append("There are no matches in this city.")

    return render(request, 'language_swap/result.html', context_dict)

def about(request):
    context_dict = {}

    return render(request, 'language_swap/about.html', context_dict)

def contact(request):
    context_dict = {}

    return render(request, 'language_swap/contact.html', context_dict)

@login_required
def profile(request):
    context_dict = {'userProfile' : {}}

    loggedUser = UserProfile.objects.get(user = request.user)

    # Get all the details of the current logged in user
    context_dict['userProfile'].update(getUserDetails(loggedUser))

    return render(request, 'language_swap/profile.html', context_dict)

@login_required
def edit_profile(request):
    loggedUser = UserProfile.objects.get(user=request.user)

    form = EditProfileForm(request.POST or None, initial={'places': loggedUser.city.title()+","+loggedUser.country.title(),
                                                          'hobby': loggedUser.hobby, 'picture': loggedUser.picture})
    if request.method == 'POST':
        if form.is_valid():
            loggedUser.city = form.cleaned_data['city']
            loggedUser.country = form.cleaned_data['country']
            loggedUser.hobby = form.cleaned_data['hobby']
            if 'picture' in request.FILES:
                loggedUser.picture.delete(save=False)
                loggedUser.picture = request.FILES['picture']
            loggedUser.save()
            return HttpResponseRedirect(reverse('myProfile'))

    context = {'form': form, 'userProfile': {}}
    # Gets all the details of the current logged in user
    context['userProfile'].update(getUserDetails(loggedUser))

    return render(request, 'language_swap/edit_profile.html', context)

@login_required
def delete_account(request):
    form = DeleteAccountForm(request.POST or None)

    if request.method == 'POST':
        if form.is_valid():
            user = request.user
            loggedUser = UserProfile.objects.get(user=user)
            loggedUser.picture.delete(save=False)
            loggedUser.delete()
            user.delete()
            return HttpResponseRedirect(reverse(index))

    context = {'form': form}
    return render(request, 'language_swap/delete_account.html', context)

@login_required
def contactHistory(request):
    context_dict = {'contacts' : {}}

    # Get the current UserProfile object
    loggedUser = UserProfile.objects.get(user = request.user)

    # Get the contact list of the users that have been contacted by the logged in user
    contactList = Contact.objects.filter(sourceUser = loggedUser)

    for contact in contactList:

        # Temporary dictionary containing all contact details
        tempDict = getUserDetails(contact.contactedUser)
        # Update the dictionary with the score assigned by the current logged in user to the specific contact
        tempDict[contact.contactedUser.user.username]['assignedScore'] = contact.score
        # Populate the context_dict with contacts details
        context_dict['contacts'].update(tempDict)

    return render(request, 'language_swap/contactHistory.html', context_dict)

# This view is used in order to perform the Ajax request to update an user rating.
# If one of the necessary steps fails, return False
@login_required
def rating(request):

    # Check if the request made is Ajax. In this way we prevent users from accessing directly to the
    # url under the name 'rating'. If the request is not Ajax, raise a Http404 error
    if request.is_ajax():

        # The resultDict is used in order to keep track of the rating process. if it fails, the
        # result value is set to False. The score key is used to store the new score for the current user
        resultDict = {'result' : False, 'score' : ''}

        loggedUser = UserProfile.objects.get(user = request.user)

        # Get the values attached to the GET request
        ratedUserId = request.GET.get('ratedUserId' , '').strip().lower()
        rating = request.GET.get('rating' , '').strip().lower()

        # Check if the values are empty or not. If they are empty, return false
        if ratedUserId and rating:
            # Try to get the ratedUser object and check if the loggedIn user has concacted it.
            # If not, return False
            try:
                rating = int(rating)
                ratedUser = User.objects.get(id = ratedUserId)
                ratedUser = UserProfile.objects.get(user = ratedUser)
                contactObject = Contact.objects.get(sourceUser = loggedUser, contactedUser = ratedUser)
            except:
                return HttpResponse(json.dumps(resultDict))
            # The rating system accepts values from 1 to 5. Therefore, check if the rating value
            # can be accepted and then set the rating of the ratedUser to be equal to rating
            # (the one specified by the loggedIn user).
            if rating in range(1,6):
                contactObject.score = rating
                contactObject.save()
                resultDict['score'] = getUserRating(ratedUser)
                resultDict['result'] = True
                return HttpResponse(json.dumps(resultDict))
            else:
                return HttpResponse(json.dumps(resultDict))
        else:
            return HttpResponse(json.dumps(resultDict))
    else:
        raise Http404

# The function checks if a given email is inside the db. If the email is contained, return 1
# otherwise return 0
def emailCheck(request):
    if request.is_ajax():
        emailList = User.objects.all().values_list('username',flat = True)
        email = request.GET.get('email','').strip().lower()

        if email in emailList:
            return HttpResponse(1)
        else:
            return HttpResponse(0)
    else:
        raise Http404


# The sendEmail function is used in order to send a mail to a User. It returns True if
# the email has been sent successfully, False otherwise.
@login_required
def sendEmail(request):
    # Check if the request performed is Ajax, if it's not raise a 404 error
    if request.is_ajax():

        # Get the contact User id and the message
        sendMessageToUser = request.GET.get('userId','').strip()
        message = request.GET.get('message','').strip()
        if sendMessageToUser and message:
            # Get the current logged In user
            loggedUser = UserProfile.objects.get(user = request.user)
            try:
                sendMessageToUser = int(sendMessageToUser)
                # Try to retrieve the user with the specified id
                contactUser = User.objects.get(id = sendMessageToUser)
                contactUser = UserProfile.objects.get(user = contactUser)
            except:
                return HttpResponse(False)
            # Send the email to the specified user, if something fails return False
            if sendEmailFunction(loggedUser, contactUser.user.email, message):

language_swap_project/templates/language_swap/about.html
{% extends 'language_swap/base.html' %}
{% block title_block %} About {% endblock %}

{% block body_block %}

    <div class="container pt-5 h-100">
        <h4 class="display-4 pb-5">About LanguageSwap</h4>
        <ul class="list-unstyled">
            <!-- List element 1 -->
            <li>
                <h4>Why should you use languageSwap when there are so many apps and tools to learn languages?</h4>
                <p class="pl-3 text-justify text-muted font-weight-light">
                    LanguageSwap allows you to meet real people and create a connection that will help you when you are struggling with the challenges of learning a new language.
                    Plus, we know that sometimes people are very worried of making mistakes when learning a new language, so meeting someone who is also trying to learn a language may help you understand that everyone struggles at something!
                </p>
            </li>
            <!-- List element 2 -->
            <li>
                <h4>Is LanguageSwap free?</h4>
                <p class="pl-3 text-muted text-justify font-weight-light">
                    Yes, of course! You will meet many people who are trying to learn like you, so nobody should charge you as if it was a tutoring lesson!
                </p>
            </li>
            <!-- List element 3 -->
            <li>
                <h4>Can I use LanguageSwap while I'm on holiday?</h4>
                <p class="pl-3 text-muted text-justify font-weight-light">
                    Sure! You could have the chance to meet a native language speaker that may guide you around the city and show you the nicest cafès in the city!
                </p>
            </li>
        </ul>
    </div>
{% endblock %}

language_swap_project/templates/language_swap/base.html
<!doctype html>
{% load staticfiles %}

<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title_block %} LanguageSwap {% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap/css/bootstrap.min.css' %}" type="text/css"></link>

    <!-- Custom styles for the templates -->
    <link href="{% static 'css/bootstrap/css/carousel.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/main_css.css' %}" rel="stylesheet" type="text/css">

    <!-- Block for customised CSS files that are needed only in specific templates. -->
    {% block specific_css %}
    {% endblock %}
</head>

<body class="bg-light">

    <header>
        <!-- Navbar -->
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
            <!-- Website name -->
            <a class="navbar-brand" href="{% url 'index' %}">LanguageSwap</a>
            <!-- Navbar collapse button -->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <!-- Navbar links -->
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav ml-auto">
                    <!-- Homepage -->
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'index' %}">Home</a>
                    </li>
                    <!-- Links available only to authenticated users -->
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'myProfile' %}">My Profile</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'contactHistory' %}">Contact History</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'auth_logout' %}?next=/LanguageSwap/">Logout</a>
                        </li>
                    <!-- Links available to guest users -->
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'auth_login' %}">Log In</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'registration_register' %}">Sign Up</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>

    {% block body_block %} {% endblock %}


    <!-- Footer -->
    <footer class="my-4 pt-3 text-right border-top">
        <ul class="list-inline mr-3">
            <li class="list-inline-item"><a href="{% url 'about' %}">About</a></li>
            <li class="list-inline-item"><a href="{% url 'contact' %}">Contact Us</a></li>
            <li class="list-inline-item"><a class="text-muted" href="#">Back to top <i class="fa fa-arrow-up"></i></a></li>
        </ul>
    </footer>

    <!-- Bootstrap core JavaScript & FontAwesome javascript-->
    <script src="{% static 'javascript/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'css/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'css/fontawesome/svg-with-js/js/fontawesome-all.js' %}"></script>

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="http://v4-alpha.getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js">
    </script>

    <!-- Block for customized javascript files that are needed only in specific templates. -->
    {% block extra_resources_block %}
    {% endblock %}
</body>

</html>

language_swap_project/templates/language_swap/contact.html
{% extends 'language_swap/base.html' %}

{% block title_block %}Contact Us{% endblock %}

{% block body_block %}
    <div class="container py-5 h-100">

        <h2 class="display-4">Meet the team</h2>
        <ul class="lead list-unstyled">
            <li>Gloria Dhandapani</li>
            <li>Martina Cocco</li>
            <li>Alessandro Speggiorin</li>
            <li>Zay Yar Tun</li>
        </ul>

        <h2 class="display-4 pt-5">Contact us</h2>
        <ul class="lead list-unstyled">
            <li><i class="far fa-envelope mr-2"></i> languageswapproject@gmail.com</li>
            <li><i class="fas fa-university mr-2"></i> University of Glasgow</li>
        </ul>


    </div>
{% endblock %}

language_swap_project/templates/language_swap/profile_cards.html
{% load staticfiles %}
<!--
Customised template tag for easy implementation of the user cards in the website.
The cards have currently a different design in each of the following pages: my profile, edit profile, search results and contact history.
To customise the templates based on the current page, a "status" variable is passed to the tag function as a parameter.
-->

<div class="card box-shadow">
    <!-- Don't show the picture while in the edit_profile page -->
    {% if status != "edit_profile" %}
        {% if details.picture %}
            <!-- Load the profile picture -->
            <img class="card-img-top img-fluid" src="{{media}}{{ details.picture }}" alt="{{details.firstname}}, profile picture">
        {% else %}
            <!-- If the picture is not present, load a placeholder -->
            <img class="card-img-top img-fluid" src="{% static 'images/placeholder.png' %}" alt="Placeholder: profile picture missing">
        {% endif %}
    {% endif %}

    <div class="card-body">
        <!-- User demographic details and rating -->
        <h3 class="card-subtitle text-muted text-capitalize text-center"id="completeName-{{details.id}}">{{details.firstname}} {{details.lastname}}</h3>
        <p class="card-text font-weight-light text-center">
            {{ details.age }}
            &#183; <!-- Unicode middle dot character -->
            {% if details.gender == "female" %}
                <i class="fa fa-venus"></i>
            {% elif details.gender == "male" %}
                <i class="fa fa-mars"></i>
            {% else %}
                <i class="fa fa-neuter"></i>
            {% endif %}
             &#183; <!-- Unicode middle dot character -->
             <span id="scoreId{{ details.id}}">
                 {% if details.score %}
                    {{ details.score }}<i class="fa fa-star golden"></i>
                 {% else %}
                    <span class="font-weight-light">
                        <em>No ratings.</em>
                    </span>
                 {% endif %}
             </span>
        </p>
    </div>

    <!-- If in the edit profile page, allows user to edit their information -->
    {% if status == "edit_profile" %}
    <form class="form" method="post" action="{% url 'edit_profile' %}" enctype="multipart/form-data">
        {% csrf_token %}
        <ul class="list-group list-group-flush list-unstyled">
            <li class="list-group-item"> <i class="fa fa-envelope"></i> Contact at <span class="text-primary">{{details.email}}</span> </li>

            <!-- Modify current location -->
            <li class="list-group-item">
                <div class="form-group">
                    <label><i class="fa fa-home"></i> From </label>
                    <input class="form-control" type="text" name="places" value="{{ details.city|title }}, {{ details.country|title }}" id="gMapsAutocomplete" required/>
                </div>
            </li>

            <!-- Modify user biography -->
            <li class="list-group-item">
                <div class="form-group">
                    <label><i class="fa fa-compass"></i> What you should know about me</label>
                    <textarea class="form-control" rows="3" type="text" name="hobby" maxlength="500" id="id_hobby">{% if details.hobby %}{{ details.hobby}}{% endif %}</textarea>
                </div>
            </li>

            <!-- Modify profile picture -->
            <li class="list-group-item pb-4">
                <div class="card-text pb-1"><i class="fas fa-camera"></i> My profile picture</div>
                <div class="custom-file">
                    <label class="custom-file-label" for="id_picture" id="id_label_picture">Change profile picture</label>
                    <input class="custom-file-input" name="picture" type="file" id="id_picture"/>
                </div>
            </li>
        </ul>


    <!-- Otherwise, show user information -->
    {% else %}
    <ul class="list-group list-group-flush list-unstyled">
        <li class="list-group-item"> <i class="fa fa-home"></i> From <span class="text-primary text-capitalize"> {{ details.city }}, {{ details.country }} </span></li>
        {% if status != "result" %}
            <li class="list-group-item"> <i class="fa fa-envelope"></i> Contact at <span class="text-primary">{{details.email}}</span> </li>
        {% endif %}
        <li class="list-group-item"> <i class="fa fa-compass"></i> What you should know about me
            {% if details.hobby %}
                <p class="pl-4 text-justify font-weight-light ">{{ details.hobby}}</p>
            {% else %}
                <p class="pl-4">-</p>
            {% endif %}
        </li>
    </ul>
    {% endif %}

    <!-- Show user languages. The edit functionality for languages is not yet implemented. -->
    <div class="card-body row text-center">
        <div class="col">
            <h6 class="card-subtitle">Speaking</h6>
            <p class="card-text text-capitalize font-weight-light">
                {% for slang in details.speaks %} {{ slang }} <br> {% endfor %}
            </p>
        </div>
        <div class="col">
            <h6 class="card-subtitle">Practicing</h6>
            <p class="text-capitalize font-weight-light">
            {% for plang in details.practices %} {{ plang }} <br> {% endfor %}
            </p>
        </div>
    </div>

    <!-- Customized footer -->

    <!-- Footer for profile page -->
    {% if status == "profile" %}
    <div class=" card-footer text-right">
        <a class="btn btn-light btn-sm text-secondary" href="{% url 'edit_profile' %}" role="button">Edit</a>
        <a class="btn btn-light btn-sm text-secondary" href="{% url 'auth_password_change' %}" role="button">Change Password</a>
        <a class="btn btn-light btn-sm text-danger" href="{% url 'delete_account' %}" role="button">Delete Account</a>
    </div>

    <!-- Footer for contact history page -->
    {% elif status == "contactHistory" %}
    <div class="card-footer">
        <span class="card-text">Rate this user:</span>
        <form class="ratingForm" method="get">
            <input type="hidden" value={{details.id}} name="ratedUserId">
            <select id="invalidSelect{{details.id}}" class="custom-select mb-2"  name="rating">
                <option {% if details.assignedScore == 0  %} selected {% endif %} disabled>You have not rated this user yet</option>
                <option {% if details.assignedScore == 1  %} selected {% endif %} value="1">1</option>
                <option {% if details.assignedScore == 2  %} selected {% endif %} value="2">2</option>
                <option {% if details.assignedScore == 3  %} selected {% endif %} value="3">3</option>
                <option {% if details.assignedScore == 4  %} selected {% endif %} value="4">4</option>
                <option {% if details.assignedScore == 5  %} selected {% endif %} value="5">5</option>
            </select>
            <div class="invalid-feedback">
                Invalid feedback
            </div>
            <button type="submit" class="btn btn-primary btn-block submit" value="Rate">Rate</button>
        </form>
    </div>

    <!-- Footer for edit profile page. The form tag is closed here for the correct functionality of the Save button. -->
    {% elif status == "edit_profile" %}
        <div class=" card-footer text-right">
            <a class="btn btn-light btn-sm text-danger" href="{% url 'myProfile' %}" role="button">Cancel</a>
            <button type="submit" class="btn btn-light btn-sm text-primary">Save</button>
        </div>
    </form>

    <!-- Footer for the search result page -->
    {% elif status == "result" %}
    <div class=" card-footer text-right">
        <!-- If the user is authenticated, allows to contact the other user -->
        {% if user.is_authenticated %}
            <button id="userContact-{{details.id}}" class="btn btn-primary btn-block sendEmail" data-toggle="modal" data-target="#sendEmailModal">Contact</button>
        <!-- Otherwise, link to the login page -->
        {% else %}
            <a href="{% url 'auth_login' %}" role="button" class="btn btn-primary btn-block">Contact</a>
        {% endif %}
    </div>
    {% endif %}

</div>